<?php foreach ($albums as $staff) : ?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png" />
    <link rel="icon" type="image/png" href="../assets/img/favicon.png" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>Material Dashboard by Creative Tim | Free Material Bootstrap Admin</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    <!-- Canonical SEO -->
    <link rel="canonical" href="https://www.creative-tim.com/product/material-dashboard"/>

    <!--  Social tags      -->
    <meta name="keywords" content="material dashboard, bootstrap material admin, bootstrap material dashboard, material design admin, material design, creative tim, html dashboard, html css dashboard, web dashboard, freebie, free bootstrap dashboard, css3 dashboard, bootstrap admin, bootstrap dashboard, frontend, responsive bootstrap dashboard">

    <meta name="description" content="Material Dashboard is a Free Material Bootstrap Admin with a fresh, new design inspired by Google's Material Design.">

    <!-- Schema.org markup for Google+ -->
    <meta itemprop="name" content="Material Dashboard by Creative Tim | Free Material Bootstrap Admin">
    <meta itemprop="description" content="Material Dashboard is a Free Material Bootstrap Admin with a fresh, new design inspired by Google's Material Design.">
    <meta itemprop="image" content="http://s3.amazonaws.com/creativetim_bucket/products/50/opt_md_thumbnail.jpg">

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@creativetim">
    <meta name="twitter:title" content="Material Dashboard by Creative Tim | Free Material Bootstrap Admin">
    <meta name="twitter:description" content="Material Dashboard is a Free Material Bootstrap Admin with a fresh, new design inspired by Google's Material Design.">
    <meta name="twitter:creator" content="@creativetim">
    <meta name="twitter:image" content="http://s3.amazonaws.com/creativetim_bucket/products/50/opt_md_thumbnail.jpg">

    <!-- Open Graph data -->
    <meta property="fb:app_id" content="655968634437471">
    <meta property="og:title" content="Material Dashboard by Creative Tim | Free Material Bootstrap Admin" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="http://demos.creative-tim.com/material-dashboard/examples/dashboard.html" />
    <meta property="og:image" content="http://s3.amazonaws.com/creativetim_bucket/products/50/opt_md_thumbnail.jpg"/>
    <meta property="og:description" content="Material Dashboard is a Free Material Bootstrap Admin with a fresh, new design inspired by Google's Material Design." />
    <meta property="og:site_name" content="Creative Tim" />

    <!-- Bootstrap core CSS     -->
    <link href="../assets/css/bootstrap.min.css" rel="stylesheet" />

    <!--  Material Dashboard CSS    -->
    <link href="../assets/css/material-dashboard.css" rel="stylesheet"/>

    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="../assets/css/demo.css" rel="stylesheet" />

    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'>
</head>

<body>

<div class="wrapper">

    <div class="sidebar" data-color="purple" data-image="../assets/img/sidebar-1.jpg">

        <div class="logo">
            <a href="/dip" class="simple-text">
                Profile
            </a>
        </div>

        <div class="sidebar-wrapper">
            <ul class="nav">
                <li class="active">
                    <a href="">
                        <i class="material-icons">dashboard</i>
                        <p>Main</p>
                    </a>
                </li>
                <li>
                    <a href="list-usr.phtml">
                        <i class="material-icons">content_paste</i>
                        <p>List of Users</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-transparent navbar-absolute">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
<!--                    <a class="navbar-brand" href="#">Material Dashboard</a>-->
                </div>
                <div class="collapse navbar-collapse">
<!--                    <ul class="nav navbar-nav navbar-right">-->
<!--                        <li>-->
<!--                            <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">-->
<!--                                <i class="material-icons">dashboard</i>-->
<!--                                <p class="hidden-lg hidden-md">Dashboard</p>-->
<!--                            </a>-->
<!--                        </li>-->
<!--                        <li class="dropdown">-->
<!--                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">-->
<!--                                <i class="material-icons">notifications</i>-->
<!--                                <span class="notification">5</span>-->
<!--                                <p class="hidden-lg hidden-md">Notifications</p>-->
<!--                            </a>-->
<!--                            <ul class="dropdown-menu">-->
<!--                                <li><a href="#">Mike John responded to your email</a></li>-->
<!--                                <li><a href="#">You have 5 new tasks</a></li>-->
<!--                                <li><a href="#">You're now friend with Andrew</a></li>-->
<!--                                <li><a href="#">Another Notification</a></li>-->
<!--                                <li><a href="#">Another One</a></li>-->
<!--                            </ul>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <a href="#pablo" class="dropdown-toggle" data-toggle="dropdown">-->
<!--                                <i class="material-icons">person</i>-->
<!--                                <p class="hidden-lg hidden-md">Profile</p>-->
<!--                            </a>-->
<!--                        </li>-->
<!--                    </ul>-->

                    <form class="navbar-form navbar-right" role="search">
                        <div class="form-group  is-empty">
                            <input type="text" class="form-control" placeholder="Search">
                            <span class="material-input"></span>
                        </div>
                        <button type="submit" class="btn btn-white btn-round btn-just-icon">
                            <i class="material-icons">search</i><div class="ripple-container"></div>
                        </button>
                    </form>
                </div>


            </div>
            <div class="content">

                <div class="container-fluid">

                    <?php
                    // module/Album/view/album/album/index.phtml:

                    $title = $this->escapeHtml($staff->display_name);
                    $this->headTitle($title);
                    ?>
                    <h1><?php echo $this->escapeHtml($title); ?></h1>
<!--                    <p>-->
<!--                        <a href="--><?php //echo $this->url('album', array('action'=>'add'));?><!--">Add new album</a>-->
<!--                    </p>-->

                    <th>&nbsp;</th>

                    <table class="table">
                        <tr>
                            <th>Name</th>
                            <td><?php echo $this->escapeHtml($staff->name);?></td>
                            <td>      <a href="<?php echo $this->url('people',
                                    array('action'=>'edit', 'id' => $album->id));?>">Edit</a></td>
                        </tr>
                        <tr>
                            <th>Date born</th>
                            <td><?php echo $this->escapeHtml($staff->dtborn);?></td>
                            <td>      <a href="<?php echo $this->url('people',
                                    array('action'=>'edit', 'id' => $album->id));?>">Edit</a></td>
                        </tr>
                        <tr>
                            <th>Country</th>
                            <td><?php echo $this->escapeHtml($staff->country);?></td>
                            <td>      <a href="<?php echo $this->url('people',
                                    array('action'=>'edit', 'id' => $album->id));?>">Edit</a></td>
                        </tr>
                        <tr>
                            <th>City</th>
                            <td><?php echo $this->escapeHtml($staff->city);?></td>
                            <td>      <a href="<?php echo $this->url('people',
                                    array('action'=>'edit', 'id' => $album->id));?>">Edit</a></td>
                        </tr>
                        <tr>
                            <th>Status</th>
                            <td><?php echo $this->escapeHtml($staff->status);?></td>
                            <td>      <a href="<?php echo $this->url('people',
                                    array('action'=>'edit', 'id' => $album->id));?>">Edit</a></td>
                        </tr>

<!--                        <pre >-->
<!--    <table class="table">-->
<!--              <thead>-->
<!--                <tr>-->
<!---->
<!--                  <th >Display name</th>-->
<!---->
<!--                </tr>-->
<!--              </thead>-->
<!--              <tbody>-->
<!--                  --><?php //foreach ($this->user as $k => $v){?>
<!--                      <tr class="success">-->
<!--                        <td>--><?php //echo $v['display_name'];?><!--</td>-->
<!--                          <td>  <button type="button"  data-toggle="collapse">-->
<!--                       Invite-->
<!--                    </button></td>-->
<!--                    </tr>-->
<!--                  --><?php //}?>
<!--              </tbody>-->
<!--        </table>-->
<!--</pre>-->


<!--                            <tr>-->
<!--                                <td>--><?php //echo $this->escapeHtml($staff->name);?><!--</td>-->
<!--                                <td>--><?php //echo $this->escapeHtml($staff->dtborn);?><!--</td>-->
<!--                                <td>--><?php //echo $this->escapeHtml($staff->country);?><!--</td>-->
<!--                                <td>--><?php //echo $this->escapeHtml($staff->city);?><!--</td>-->
<!--                                <td>--><?php //echo $this->escapeHtml($staff->display_name);?><!--</td>-->
<!--                                <td>--><?php //echo $this->escapeHtml($staff->status);?><!--</td>-->
<!--                                <td>-->
<!--                                    <a href="--><?php //echo $this->url('album',
//                                        array('action'=>'edit', 'id' => $album->id));?><!--">Edit</a>-->
<!--                                    <a href="--><?php //echo $this->url('album',
//                                        array('action'=>'delete', 'id' => $album->id));?><!--">Delete</a>-->
<!--                                </td>-->
<!--                            </tr>-->
                        <?php endforeach; ?>
                    </table>

                </div>
            </div>
        </nav>

        <div class="content">

            <div class="container-fluid">

                <div class="row">

                 </div>

            </div>
        </div>

        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="#">
                                Home
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Company
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Portfolio
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Blog
                            </a>
                        </li>
                    </ul>
                </nav>
                <p class="copyright pull-right">
                    &copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
                </p>
            </div>
        </footer>
    </div>

</div>



</body>



</html>
