
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png" />
    <link rel="icon" type="image/png" href="../assets/img/favicon.png" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>Diplomizer</title>

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'>
</head>

<body>

<div class="wrapper">

    <div class="sidebar" data-color="purple" data-image="../assets/img/sidebar-1.jpg">

        <div class="logo">
            <a href="#" class="simple-text">
                Diplomizer
            </a>
        </div>

        <div class="sidebar-wrapper">
            <ul class="nav">
                 <li>
                    <a href="/people">
                        <i class="material-icons">person</i>
                        <p>User Profile</p>
                    </a>
                </li>
                <li>
                    <a href="list-usr.phtml">
                        <i class="material-icons">content_paste</i>
                        <p>List of Users</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>


</div>

</body>

</html>
